export const GroupActionTypes = {
  FETCH_GROUP_START: "FETCH_GROUP_START",
  FETCH_GROUP_START_ASYNC: "FETCH_GROUP_START_ASYNC",
  FETCH_GROUP_SUCCESS: "FETCH_GROUP_SUCCESS",
  FETCH_GROUP_FAILURE: "FETCH_GROUP_FAILURE",
};
