export const CreateGroupActionTypes = {
  FETCH_CREATE_GROUP_START: "FETCH_CREATE_GROUP_START",
  FETCH_CREATE_GROUP_START_ASYNC: "FETCH_CREATE_GROUP_START_ASYNC",
  FETCH_CREATE_GROUP_SUCCESS: "FETCH_CREATE_GROUP_SUCCESS",
  FETCH_CREATE_GROUP_FAILURE: "FETCH_CREATE_GROUP_FAILURE",
};
