export const DeleteGroupActionTypes = {
  FETCH_DELETE_GROUP_START: "FETCH_DELETE_GROUP_START",
  FETCH_DELETE_GROUP_START_ASYNC: "FETCH_DELETE_GROUP_START_ASYNC",
  FETCH_DELETE_GROUP_SUCCESS: "FETCH_DELETE_GROUP_SUCCESS",
  FETCH_DELETE_GROUP_FAILURE: "FETCH_DELETE_GROUP_FAILURE",
};
