export const EditGroupActionTypes = {
  FETCH_EDIT_GROUP_START: "FETCH_EDIT_GROUP_START",
  FETCH_EDIT_GROUP_START_ASYNC: "FETCH_EDIT_GROUP_START_ASYNC",
  FETCH_EDIT_GROUP_SUCCESS: "FETCH_EDIT_GROUP_SUCCESS",
  FETCH_EDIT_GROUP_FAILURE: "FETCH_EDIT_GROUP_FAILURE",
};
