export const ProfileActionTypes = {
    FETCH_PROFILE_START: "FETCH_PROFILE_START",
    FETCH_PROFILE_START_ASYNC: "FETCH_PROFILE_START_ASYNC",
    FETCH_PROFILE_SUCCESS: "FETCH_PROFILE_SUCCESS",
    FETCH_PROFILE_FAILURE: "FETCH_PROFILE_FAILURE",
};