export const EditProfileActionTypes = {
    FETCH_EDIT_PROFILE_START: "FETCH_EDIT_PROFILE_START",
    FETCH_EDIT_PROFILE_START_ASYNC: "FETCH_EDIT_PROFILE_START_ASYNC",
    FETCH_EDIT_PROFILE_SUCCESS: "FETCH_EDIT_PROFILE_SUCCESS",
    FETCH_EDIT_PROFILE_FAILURE: "FETCH_EDIT_PROFILE_FAILURE",
};